# Generated by Django 4.1.3 on 2022-12-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients_Details',
            fields=[
                ('p_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('p_fname', models.CharField(max_length=50)),
                ('p_lname', models.CharField(max_length=50)),
                ('contact_no', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('pregnancies', models.PositiveIntegerField()),
                ('glucose', models.PositiveIntegerField()),
                ('blood_pressure', models.PositiveIntegerField()),
                ('insulin', models.PositiveIntegerField()),
                ('bmi', models.CharField(max_length=6)),
                ('dpf', models.CharField(max_length=6)),
                ('date', models.DateField()),
            ],
        ),
    ]
