# Generated by Django 4.1.3 on 2022-12-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patients_details_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients_details',
            name='skin_thikness',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
