# Generated by Django 4.1.5 on 2023-04-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patients_details_skin_thikness'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients_details',
            name='precautions',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
